# Numpy
- python에서 사용하는 과학계산용 오픈소스 라이브러리
- python의 느린 연산속도를 보안
- ndarray라는 데이터 타입을 사용합니다.
- C, C++, 포트란으로 만들어짐

## 선형대수
- 스칼라(scalar)
    - 하나의 숫자로만 이루어진 데이터
    - ex) 1
- 벡터(vector)
    - 여러 개의 숫자가 특정한 순서대로 모여 있는 것
    - ex) [1, 2, 3]
    -  $\mathbf{V} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$
- 행렬(matrix)
    - 2차원 배열로 구성
    - 행(rows)와 열(columns)
    - 행렬 [[1, 2, 3], [4, 5, 6]]

In [100]:
import numpy as np

### 01. ndarray 객체 생성

In [4]:
scalar = np.array(5)
type(scalar)

numpy.ndarray

In [5]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# 배열의 차원 확인
scalar.ndim, vector.ndim, matrix.ndim

(0, 1, 2)

In [12]:
# 배열의 모양 확인
scalar.shape, vector.shape, matrix.shape

((), (3,), (3, 3))

In [17]:
# 문자열도 배열 데이터 생성 가능
str_vector = np.array(list('ABCD'))
str_vector

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [18]:
ls = [1, 2, 3, 'D']
ls

[1, 2, 3, 'D']

In [20]:
type(ls[-1]), type(ls[0])

(str, int)

In [22]:
# numpy는 한가지 데이터 타입으로만 인식
np.array(ls)

array(['1', '2', '3', 'D'], dtype='<U21')

In [25]:
# 데이터 타입 변경
# astype()
np.array([1, 2, 3, '4']).astype(np.float64)

array([1., 2., 3., 4.])

### 02. np.arange()

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(1, 5, 2)

array([1, 3])

### 03. np.zeros(), np.ones()
- zeros : 0으로 채워진 행렬 데이터
- ones : 1로 채워진 행렬 데이터
- 초기화 값을 지정할 경우 활용

In [35]:
mat_zero = np.zeros((2,2,3))  # 
mat_zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
mat_ones = np.ones((2,2,3))
mat_ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### 04. np.random()

In [76]:
# 정수 데이터 타입을 균일분포로 생성
np.random.randint(10, size = (2, 3))

array([[7, 9, 2],
       [5, 2, 6]])

In [92]:
# seed()
# seed 값을 고정하면 동일한 랜덤값 출력

np.random.seed(13)
np.random.randint(0, 10, 10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])

In [111]:
# (1) 0 ~ 4까지의 숫자중 한개 선택
# (2) 반환할 샘플의 갯수, 10개
# (3) 선택 확률 지정
# (4) 선택할 수 있는 값('p='을 말함)의 배열과 길이가 동일해야 합니다.

np.random.choice(5, 10, p = [0.1, 0, 0.3, 0.6, 0])

array([3, 3, 3, 3, 2, 2, 3, 2, 3, 2])

### 05. np.linspace()
```python
np.linspace(start, stop, num=50, endpoint=True)
```
- 시작값과 종료값 사이에서 지정된 갯수만큼 균등간격으로 선형적으로 분포하는 값을 생성
- endpoint : True로 설정하면, stop 값을 배열에 포함 

In [115]:
len(np.linspace(10, 20))

50

In [120]:
np.linspace(10, 20, 11, False)

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909])

### 06. adarray 객체에서 데이터 선택
- 오프셋 인덱스, 인덱싱, 슬라이싱

In [124]:
# 0부터 9까지 랜덤한 정수값을 가진 열 벡터 생성
vec = np.random.randint(10, size=10)
vec

array([1, 6, 8, 6, 6, 8, 6, 8, 0, 2])

In [130]:
# 처음부터 시작하고, 3번째 인덱스 값까지 선택해주세요 (
# 3번째 인덱스면 3, 즉 프로그램 실행시 2번 인덱스까지 나오도록 약속)
vec[:3]

array([1, 6, 8])

In [139]:
# 역순에서 3번째 값부터 시작하고, 끝까지 선택
vec[-3:]

array([8, 0, 2])

In [136]:
# 역순에서 4번째 값
vec[-4]

6

In [142]:
# 처음부터 끝까지 데이터를 선택하는데. 역순으로 2단계씩 건너띄어주세요
vec[::-2]

array([2, 8, 8, 6, 6])

#### 행렬에서 슬라이싱(1)

In [144]:
mat = np.random.randint(5, size = (3, 3))
mat

array([[4, 2, 4],
       [2, 4, 2],
       [0, 0, 4]])

In [147]:
mat[0]

array([4, 2, 4])

In [148]:
mat[0][1]

2

In [150]:
# numpy에서 이런식으로 작성이 가능
mat[0, 1]

2

#### 행렬에서 슬라이싱(2)

In [155]:
# 1부터 25까지의 정수가 담긴 열 백터 생성
vec = np.arange(1, 26)
vec
len(vec)

25

In [163]:
# 5 x 5,  5 by 5 형태로 변환
mat = vec.reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [166]:
# 첫 번째 행 전체 선택
mat[0, :]

array([1, 2, 3, 4, 5])

In [167]:
mat[0]

array([1, 2, 3, 4, 5])

In [175]:
# 세 번째 열 전체 선택

mat[:, 2]

array([ 3,  8, 13, 18, 23])

In [176]:
mat[1:3, :]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [178]:
mat[: , 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [186]:
# 두 번째 행부터 세 번째 행
# 두 번째 열부터 세 번째 열

mat[1:3, 1:4]

(array([[ 7,  8,  9],
        [12, 13, 14]]),
 array([16, 17]))

In [192]:
# 행을 역순으로 변환
mat [ :: -1, :]
               

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### 07. np.reshape()

```python
np.reshape(array, newshape)
```
- a(array) : 형태를 변경할 배열
- newshape
    - 새로운 형태로 재구성할 배열의 차원을 지정 -> tuple
    - (3, 4)는 3행 4열
    - (6, 2)는 6행 2열

In [194]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [196]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [197]:
np.reshape(a, (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
b = np.arange(10)
b.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [211]:
# -1
# 행은 3개로 설정하는데, 열은 자동으로 설정
a.reshape(3, -1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [217]:
# 이미지 데이터
# 이미지는 3차원 데이터 배열
image = np.random.randint(0, 255, size=(32, 32, 3), dtype=np.uint8)
image

array([[[136,  72, 171],
        [ 47, 168,  86],
        [ 73, 188, 101],
        ...,
        [225,  82, 131],
        [219, 249, 113],
        [143,  61, 154]],

       [[ 80, 225,  91],
        [148, 143, 247],
        [ 75, 193, 125],
        ...,
        [ 27,  14, 102],
        [114, 152,  10],
        [103,   2,  49]],

       [[126,  41, 204],
        [ 24, 155,  91],
        [ 67, 186, 200],
        ...,
        [238, 164, 186],
        [ 19,  12, 180],
        [ 53,  99,  43]],

       ...,

       [[135,   6,  13],
        [209, 156, 224],
        [124, 142, 213],
        ...,
        [175, 179,  19],
        [106, 167,  61],
        [250, 253,  80]],

       [[ 83,  23,  91],
        [201,  51,  15],
        [ 99, 197,  10],
        ...,
        [218, 230, 153],
        [180, 188,  77],
        [ 39,  72, 197]],

       [[ 53,  69, 226],
        [177,  93, 142],
        [112, 170, 110],
        ...,
        [233, 252,   3],
        [ 61, 177, 230],
        [220, 244, 204]]

In [218]:
image.shape

(32, 32, 3)

In [219]:
# 2차원 배열로 변환
image.reshape(32*32, 3)

array([[136,  72, 171],
       [ 47, 168,  86],
       [ 73, 188, 101],
       ...,
       [233, 252,   3],
       [ 61, 177, 230],
       [220, 244, 204]], dtype=uint8)

### 08. np.where()

```python
np.where(condition, x, y)
```
- 조건에 따라 값을 선택
- condition
    - 조건을 나타내는 배열 또는 조건문
    - True or False
- x, y는 서로 동일한 크기(shape) 배열 형태
- condition이 True인 경우 x값 반환
- condition이 False인 경우 y값 반환

In [8]:
import numpy as np
condition = [True, False, True]
x = [1, 2, 3]
y = [10, 20, 30]


In [9]:
np.where(condition, x, y)

array([ 1, 20,  3])

In [10]:
a = [x[i] if condition[i] else y[i] for i in range(len(condition))]
# a = []
# for i in range(len(condition)):
#     a.append(x[i] if condition[i] else y[i])
print(a)

[1, 20, 3]


In [11]:
for con, xv, yv in list(zip(condition, x, y)):
    print(con, xv, yv)

True 1 10
False 2 20
True 3 30


In [12]:
result = [xv if con else yv for con, xv, yv in zip( condition, x, y)]
result

[1, 20, 3]