# Numpy
- python에서 사용하는 과학계산용 오픈소스 라이브러리
- python의 느린 연산속도를 보안
- ndarray라는 데이터 타입을 사용합니다.
- C, C++, 포트란으로 만들어짐

# 선형대수
- 스칼라(scalar)
  - 하나의 숫자로만 이루어진 데이터
  - ex)1
- 벡터(vector)
  - 여러 개의 숫자가 특정한 순서대로 모여 있는 것
  - ex)[1, 2, 3]
  - V = [1, 2, 3]
- 행렬(matrix)
  - 2차원 배열로 구성
  - 행(rows)와 열(columns)로 구성
  - 행렬[[1, 2, 3], [4, 5, 6]]

In [1]:
import numpy as np

## 01. ndarray 객체 생성

In [2]:
scalar = np.array(5)
type(scalar)

numpy.ndarray

In [3]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
# 배열의 차원 확인 
scalar.ndim, vector.ndim, matrix.ndim

(0, 1, 2)

In [9]:
# 배열의 모양 확인
scalar.shape, vector.shape, matrix.shape

((), (3,), (4, 3))

In [11]:
# 문자열도 배열 데이터 생성 가능
str_vector = np.array(list('ABCD'))
str_vector

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [12]:
str_vector.shape

(4,)

In [13]:
ls = [1, 2, 3, 'D']
ls


[1, 2, 3, 'D']

In [14]:
type(ls[-1]), type(ls[0])

(str, int)

In [15]:
# numpy는 한 가지 데이터 타입으로만 인식 질문!!
np.array(ls)

array(['1', '2', '3', 'D'], dtype='<U21')

In [16]:
# 데이터 타입 변경
# astype()
np.array([1, 2, 3, '4']).astype(np.float64)

array([1., 2., 3., 4.])

## 02. np.arrange()

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(1, 5, 2)

array([1, 3])

## 03. np.zeros(), np.ones()
- zeros : 0으로 채워진 행렬 데이터
- ones : 1로 채워진 행렬 데이터
- 초기화 값을 지정할 경우 활용

In [20]:
mat_zero = np.zeros((2, 2, 3))
mat_zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
mat_ones = np.ones((2, 2, 3))

In [22]:
mat_ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
mat_ones.ndim, mat_ones.shape

(3, (2, 2, 3))

## 04.np.random()

In [25]:
# 정수 데이터 타입을 균일 분포로 생성
np.random.randint(10, size = (2, 3))

array([[4, 6, 6],
       [2, 9, 7]])

In [26]:
# seed()
# seed 값을 고정하면 동일한 랜덤값 출력

np.random.seed(13)
np.random.randint(0, 10, 10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])

In [27]:
# 1. 0~ 4까지의 숫자중 한 개 선택
# 2. 반환할 샘플의 갯수, 10개
# 3. 선택 확률 지정
# 4. 선택할 수 있는 값(p를 말함)의 배열과 길이가 동일해야 함

np.random.choice(5, 10, p = [0.1, 0, 0.3, 0.6, 0])

array([3, 2, 2, 3, 3, 3, 3, 3, 3, 3])

## 05. np.linspace()
```python
np.linspace(start, stop, num = 50, endpoint = True)
```
- 시작값과 종료값 사이에서 지정된 갯수만큼 균등간격으로 선형적으로 분포하는 값을 생성
- endpoint : True로 설정하면, stop 값을 배열에 포함

In [28]:
len(np.linspace(10, 20))

50

In [29]:
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [34]:
np.linspace(10, 20, 11, False)

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909])

## 06. adarray 객체에서 데이터 선택
- 오프셋 인덱스, 인덱싱, 슬라이싱

In [47]:
# 0부터 9까지 랜덤한 정수값을 가진 열 벡터 생성
vec = np.random.randint(10, size = 10)
vec

array([8, 5, 1, 8, 1, 7, 7, 5, 6, 3])

In [48]:
# 처음부터 시작하고, 3번째 인덱스 값까지 선택해주세요
# 3번째 인덱스면 3, 즉 프로그램 실행시 2번 인덱스까지 나오도록 약속
vec[:3]

array([8, 5, 1])

In [49]:
list(vec)

[8, 5, 1, 8, 1, 7, 7, 5, 6, 3]

In [50]:
vec

array([8, 5, 1, 8, 1, 7, 7, 5, 6, 3])

In [43]:
# 역순에서 3번째 값부터 시작하고, 끝까지 선택
vec[-3:]

[5, 8, 3]

In [51]:
vec[-4]

7

In [52]:
# 처음부터 끝까지 데이터를 선택하는데, 역순으로 2단계씩 건너띄어주세요
vec[::-2]

array([3, 5, 7, 8, 5])

### 행렬에서 슬라이싱 1

In [53]:
mat = np.random.randint(5, size = (3, 3))
mat

array([[3, 3, 0],
       [2, 0, 2],
       [4, 3, 0]])

In [54]:
mat[0]

array([3, 3, 0])

In [55]:
mat[0][1]

3

In [56]:
# numpy에서 이런식으로 작성이 가능
mat[0, 1]

3

### 행렬에서 슬라이싱 2 

In [58]:
# 1 부터 25까지의 정수가 담긴 열 벡터 생성
vec = np.arange(1, 26)
vec
len(vec)

25

In [59]:
vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [60]:
# 5 X 5, 형태로 변환
mat = vec.reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
# 첫 번째 행 전체 선택
mat[0, :]

array([1, 2, 3, 4, 5])

In [62]:
mat[0]

array([1, 2, 3, 4, 5])

In [63]:
# 세 번째 열 전체 선택

mat[:, 2]

array([ 3,  8, 13, 18, 23])

In [65]:
# 3행 3열 4행 3열 
mat[2:4, 2]

array([13, 18])

In [66]:
mat[1:3, :] # 2행 3행 전체

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [67]:
mat[:, 1:4] # 2열 3열 4열 전체

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [68]:
# 두 번째 행부터 세 번째 행
# 두 번째 열부터 네 번째 열

mat[1:3, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [73]:
# 행을 역순으로 변환
mat[ :: -1, :]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

## 07.np.reshape()
```python
np.reshape(array, newshape)
```
- a(array): 형태를 변경할 배열
- newshape
    - 새로운 형태로 재구성할 배열의 차원을 지정 > tuple
    - (3, 4)는 3행 4열
    - (6, 2)는 6행 2열

In [74]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
a.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
np.reshape(a, (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
b = np.arange(10)
b.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [78]:
# 1
# 행은 3개로 설정하는데, 열은 자동으로 설정
a.reshape(3, -1)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
# 이미지 데이터
# 이미지는 3차원 데이터 배열

In [80]:
image = np.random.randint(0, 255, size = (32, 32, 3), dtype=np.uint8)  # 32 by 3 행렬이 32개 
image

array([[[ 85, 138, 195],
        [175, 175, 245],
        [149,  62, 217],
        ...,
        [ 25, 199, 245],
        [224, 182,  59],
        [246, 220,  62]],

       [[244, 215, 213],
        [ 52, 154, 125],
        [219,  38,  53],
        ...,
        [ 48,  91, 196],
        [252, 128, 134],
        [151, 154, 125]],

       [[237,   9, 102],
        [118, 189,  58],
        [ 71, 182, 248],
        ...,
        [ 60, 246, 161],
        [ 60,  10, 191],
        [ 21, 108, 152]],

       ...,

       [[117, 173, 161],
        [147, 177, 132],
        [ 84, 168, 217],
        ...,
        [243,  26,  78],
        [190,   5, 208],
        [ 30,  55, 206]],

       [[209, 208,  36],
        [230, 241,  69],
        [  3, 224, 193],
        ...,
        [ 41, 146,  20],
        [203, 126,  77],
        [146, 119, 131]],

       [[164, 118, 200],
        [ 20,  83,   2],
        [172,  95, 253],
        ...,
        [193, 169, 201],
        [227,   4,  97],
        [ 91, 218,  72]]

In [81]:
image.shape

(32, 32, 3)

In [82]:
# 2차원 배열로 변환
image.reshape(32*32, 3)

array([[ 85, 138, 195],
       [175, 175, 245],
       [149,  62, 217],
       ...,
       [193, 169, 201],
       [227,   4,  97],
       [ 91, 218,  72]], dtype=uint8)

## 08.np.where()
```python
np.where(condition, x, y)
```
- 조건에 따라 값을 선택
- condition
    - 조건을 나타내는 배열 또는 조건문
    - True or False
- x, y는 서로 동일한 크기(shape)배열 형태
- condition이 True인 경우 x값 반환
- condition이 False인 경우 y값 반환

In [84]:
import numpy as np
condition = [True, False, True]
x = [1, 2, 3]
y = [10, 20, 30]

In [85]:
np.where(condition, x, y)

array([ 1, 20,  3])